customer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('web.urls', namespace='web')),
    path('events/', include('events.urls', namespace='events')),
    path('update/', include('info.urls', namespace='info')),
]

users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

web/urls.py
from django.urls import path

from web import views


app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.sort, name='sort')
]

users/models.py
from django.db import models


class Customer(models.Model):
    number = models.IntegerField()
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.TextField()
    date_of_birth = models.DateField()
    password = models.CharField(max_length=255)
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    event = models.ManyToManyField('events.Events')

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms

from users.models import Customer


class UserForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['full_name', 'phone', 'email', 'address', 'date_of_birth', 'password']

        

users/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User

from users.forms import UserForm, Customer


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                url = f'/{user.pk}'
                return HttpResponseRedirect(url)
            
        context = {
            'title' : 'Login',
            'error' : True,
            'message' : 'Invalid username or password',
        }
        return render(request, 'users/login.html', context=context)
    
    else:
        context = {
            'title' : 'Login',
        }
        return render(request, 'users/login.html', context=context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('web:index'))


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username = instance.full_name,
                password = instance.password
            )

            customer = Customer.objects.create(
                number = user.id,
                full_name = user.username,
                phone = instance.phone,
                email = instance.email,
                address = instance.address,
                date_of_birth = instance.date_of_birth,
                user = user
            )

            user = authenticate(request, username = instance.full_name, password = instance.password)
            auth_login(request, user)

            url = f'/{customer.number}'
            return HttpResponseRedirect(url)
        
        context = {
            'title' : 'Signup',
            'error' : True,
        }
        return render(request, 'users/signup.html', context=context)
    
    else:
        form = UserForm()
        context = {
            'title' : 'Signup',
            'form' : form,
            'error' : True,
            'message' : 'Username already exists'
        }
        return render(request, 'users/signup.html', context=context)


    

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css" />
        <title>{{title}}</title>
    </head>
    <body>
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h4 class="card-title text-center">Login</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" name="username" class="form-control" id="username" placeholder="Enter username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="Enter password" required>
                        </div>
                        {% if error %}
                            <p>{{message}}</p>
                        {% endif %}
                        <div class="gap-2">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <a class="btn btn-danger" href="{% url 'users:signup' %}">Signup</a>
                        </div>
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css" />
        <title>{{title}}</title>
    </head>
    <body>
        <div class="container mt-5">
            <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h4 class="card-title text-center">Signup</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <label for="name">Full Name : </label>
                            <input class="mb-3 form-control" type="text" placeholder="Full Name" id="name" name="full_name" required />
                            <label for="name">Phone Number : </label>
                            <input class="mb-3 form-control" type="tel" pattern="[0-9]+" placeholder="Phone Number" id="phone" name="phone" 
                            oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" maxlength="10" required /> 
                            <label for="email">Email Address : </label>
                            <input class="mb-3 form-control" type="email" placeholder="Email" id="email" name="email" pattern="[a-zA-Z0-9.-_]{1,}@[a-zA-Z.-]{2,}[.]{1}[a-zA-Z]{2,}"/>
                            <label for="dob">Date of birth : </label>
                            <input class="mb-3 form-control" type="date" id="date" name="date_of_birth" required />
                            <label for="adress">Address : </label>
                            <textarea class=" mb-3 form-control" id="address" name="address" placeholder="Address" required ></textarea>
                            <label for="password">Password : </label>
                            <input class="form-control mb-3" type="password" placeholder="Password (must have 6 characters)" id="password" name="password" required />
                            
                            <button type="submit" value="signup" class="btn btn-primary">Create account</button>
                            <a class="btn btn-danger" href="{% url 'users:login' %}">Login</a>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </body>
</html>