customer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('web.urls', namespace='web')),
    path('events/', include('events.urls', namespace='events')),
    path('update/', include('info.urls', namespace='info')),
]

events/urls.py
from django.urls import path

from events import views


app_name = 'events'

urlpatterns = [
    path('add_event/', views.add_event, name='add_event'),
    path('edit_event/<int:id>', views.edit_event, name='edit_event'),
    path('delete_event/<int:id>', views.delete_event, name='delete_event'),
    path('go/', views.go_back, name='go_back'),
]

users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

web/urls.py
from django.urls import path

from web import views


app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.sort, name='sort')
]

events/models.py
from django.db import models


class Events(models.Model):
    id = models.AutoField(primary_key=True)
    event_name  = models.CharField(max_length=255)
    event_date = models.DateField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.event_name

events/forms.py
from django import forms

from events.models import Events


class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['event_name', 'event_date']

        widgets = {
            'event_name' : forms.TextInput(attrs={'required': 'False'}),
            'event_date' : forms.DateInput(attrs={'required': 'False'})
        }

events/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect

from events.forms import EventForm
from users.models import Customer
from events.models import Events


def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        customer = Customer.objects.get(number=request.user.id)
        
        if form.is_valid():
            instance = form.save(commit=False)
            events, created = Events.objects.get_or_create(
                event_name = instance.event_name,
                event_date = instance.event_date
            )

            customer.event.add(events)
            url = f'/{request.user.id}'
            return HttpResponseRedirect(url)
        
        else:
            form = EventForm()
            context = {
                'title' : 'Add Event',
                'form' : form,
                'error' : True,
                'message' : 'Event error'
            }
            return render(request, 'events/add_event.html', context=context)       

    else:
        form = EventForm()
        context = {
            'title' : 'Add Event',
            'form' : form,
            'error' : True,
            'message' : 'Event error'
        }
        return render(request, 'events/add_event.html', context=context)
    

def edit_event(request, id):
    instance = get_object_or_404(Events, id=id)

    if request.method == 'POST':
        instance = get_object_or_404(Events, id=id)
        form = EventForm(request.POST, request.FILES, instance=instance)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()

            url = f'/{request.user.id}'
            return HttpResponseRedirect(url)
        
    else:
        form = EventForm()
        context = {
            'title' : 'Edit Event',
            'form' : form,
            'error' : True,
            'message' : 'Event error',
            'instances' : instance
        }
        return render(request, 'events/edit_event.html', context=context)


def delete_event(request, id):
    instance = get_object_or_404(Events, id=id)
    instance.is_deleted=True
    instance.save()

    url = f'/{request.user.id}'
    return HttpResponseRedirect(url)


def go_back(request):
    url = f'/{request.user.id}'
    return HttpResponseRedirect(url)

templates/events/add_event.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css" />
        <title>{{title}}</title>
    </head>
    <body>
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h4 class="card-title text-center">Add Event</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="event" class="form-label">Event : </label>
                                <input type="text" name="event_name" class="form-control" placeholder="Type event" required>
                            </div>
                            <div class="mb-3">
                                <label for="date" class="form-label">Date : </label>
                                <input type="date" name="event_date" class="form-control" required>
                            </div>
                            <input class="btn btn-primary" type="submit" value="Add event" />
                            <a href="{% url 'events:go_back' %}">Maybe,later</a>
                            {% if instance.error %}
                                <p class="error-message">An Error Occured</p>
                            {% endif %}
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/events/edit_event.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css" />
        <title>{{title}}</title>
    </head>
    <body>
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h4 class="card-title text-center">Add Event</h4>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="event" class="form-label">Event : </label>
                                <input type="text" name="event_name" class="form-control" placeholder="Type event" value="{{instances.event_name}}"/>
                            </div>
                            <div class="mb-3">
                                <label for="date" class="form-label">Date : </label>
                                <input type="date" name="event_date" class="form-control" value="{{instances.event_date|date:'Y-m-d'}}" />
                            </div>
                            <input class="btn btn-primary" type="submit" value="Add event" />
                            {% if instance.error %}
                                <p class="error-message">An Error Occured</p>
                            {% endif %}
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/events/item.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css" />
        <link rel="stylesheet" href="../../static/css/responsive.css" />
        <title>{{title}}</title>
        </head>
    <body>
        <section id="customer">
            <section class="p-5 m-2">
                <div class="d-flex align-items-center mb-3">
                    <a href="#" style="text-decoration: none;"><h1>{{instances.full_name}}</h1></a>
                    <a class="btn btn-primary mx-3" href="{% url 'users:logout' %}" style="height: 5vh;">Logout</a>
                </div>
                <a class="btn btn-success my-2" href="{% url 'events:add_event' %}">Add Events</a>
                <div class="d-flex justify-content-between">
                    <div>
                        <div> 
                            <ul>
                                <h3 style="margin: 10px -33px;">EVENTS</h3>
                                {% for event in events.all %}
                                    <li class="d-flex" style="width: 150%;">
                                        <div style="width: 30%; text-align: left;">
                                            <h5 style="display: list-item;">{{event.event_name}}</h5>
                                        </div>
                                        <div style="width: 35%; text-align: left;">
                                            <h5 class="mx-5">{{event.event_date}}</h5>
                                        </div>
                                        <div class="d-flex mx-5">
                                            <div>
                                                <a href="{% url 'events:edit_event' id=event.id %}">
                                                    <img src="{% static '../../static/images/edit.png' %}" width="20" >
                                                </a>
                                            </div>
                                            <div class="mx-3">
                                                <a href="{% url 'events:delete_event' id=event.id %}">
                                                    <img src="{% static '../../static/images/trash.png' %}" width="20" >
                                                </a>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="mx-5 px-5" style="margin-top: -100px;">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                            <h4 class="card-title">Personal Info</h4>
                            <p class="card-text">Here's your login details. You can still update it, if you want.</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Name: {{instances.full_name}}</li>
                                <li class="list-group-item">Phone: {{instances.phone}}</li>
                                <li class="list-group-item">Email: {{instances.email}}</li>
                                <li class="list-group-item">DOB: {{instances.date_of_birth}}</li>
                                <li class="list-group-item">Address: {{instances.address}}</li>
                            </ul>
                            <div class="card-body">
                            <a href="/update/{{instances.id}}" class="btn btn-info">Update</a>
                            </div>
                        </div>   
                        <form action="" method="" class="mt-3">
                            <h2>Sort Events by</h2>
                            <div>
                                <input type="radio" id="Today" name="sort" value="today" >
                                <label for="today">Today</label>
                            </div>
                            <div>
                                <input type="radio" name="sort" value="this-month" >
                                <label for="this-month">This month</label>
                            </div>
                            <div class="mb-2">
                                <input type="radio" name="sort" value="all" >
                                <label for="all">All</label>
                            </div>
                            <input class="btn btn-warning" type="submit" value="Filter" style="padding: 10px 40px;"/>
                            {% if instance.error %}
                                <p class="error-message">An Error Occured</p>
                            {% endif %}
                        </form>                   
                    </div>  
                </div>
            </section>
        </section>
    </body>
</html>